### PR TITLE
Add safe-area example and also add support for subtitle in the unified and expanded toolbar types

### PR DESCRIPTION
**Pull request by JoshBashed**
I found it confusing to implement a safe area, and there were no docs so I added an example.

I was kind of annoyed that there's no subtitle feature, so I added it in the window

### CODE REVIEW

**Comment by ryanmcgrath** [comment]
Awesome, thanks!

**Comment by ryanmcgrath** [comment]
Ah, damn, no idea why GitHub said things passed and then... failed all the CI tests.

I guess I'll fix the errors out of band since it's already merged...

**Comment by JoshBashed** [comment]
It worked on my system.
2023年4月24日 +0800 PM4:44 Ryan McGrath ***@***.***>，写道：

**Comment by ryanmcgrath** [comment]
No worries - one is just a formatting pass that it should've alerted about needing, the other is... I dunno what exactly but I'll handle it in the morning.

**Pull request merged**
